feat: Этап 2. Основной сервис
OxanaKutukova/java-explore-with-me pull request #2
Opened 2023-02-26 13:13 UTC by OxanaKutukova

2023-02-26 19:57 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-26 19:57 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/service/compilation/service/CompilationServiceImpl.java
> +        if (compilationS.getEvents().size() > 0) {
Очень запутано на 37 строке... 
Главная причина: несколько цепочек в одной строке.
Чтобы этого избежать - вынесем получение в отдельный метод.
 
Код мог бы выглядеть так:

```
    public CompilationDto create(NewCompilationDto newCompilationDto) {
        final Compilation newCompilation = compilationRepository.save(toCompilation(newCompilationDto));

        if (newCompilation.getEvents().size() > 0) {
            newCompilation.getEvents()
                          .replaceAll(this::getEvent);
        }

        return toCompilationDto(newCompilation);
    }

    private Event getEvent(Event event) {
        return eventRepository.findById(event.getId())
                              .orElseThrow(() -> new NotFoundException("Событие не найдено или недоступно"));
    }
```

2023-02-26 19:57 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/service/compilation/dto/NewCompilationDto.java
> +    private String title;
Кажется не хватает проверок... 
У тебя title не может быть более 120 символов, например...

2023-02-26 19:57 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/service/event/service/EventService.java
> +    List<EventFullDto> getAllAdmin(Optional<List<Long>> users, Optional<List<String>> states, Optional<List<Long>> categories, Optional<String> rangeStart, Optional<String> rangeEnd, Pageable pageabl
Не бывает `Optional<List<Long>>`  ! 
Ну т.е. технически, как мы видим, это возможно! )))
Но на практике в этом нет нужды, ведь для списка вполне естественно быть просто пустым.

Отсюда, кстати, и правило: не возвращать вместо списка `null`, а всегда возвращать пустой список вместо этого.

2023-02-26 19:57 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/service/request/service/RequestServiceImp.java
> +            throw new BadRequestException("Значение ид события не может быть пустым");
А почему это в сервисе?
Проверить входные параметры это обязанность контроллера - это туда! )

Вот следующие проверки, где `ValidationException` - это тут, потому что это уже сценарии бизнес-логики.

2023-02-26 19:57 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/service/user/repository/UserRepository.java
> +    List<User> findAllInId(List<Long> ids, Pageable pageable);
Такой запрос можно было бы собрать и стандартными средствами.
Это не ошибка, просто можешь потренироваться! ))

2023-02-26 19:57 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/service/user/service/UserServiceImpl.java
> +        users = (ids == null) ? userRepository.findAll(pageable).getContent()
тернарник к месту, но лучше расположить вот так:

```
        users = (ids == null) 
                ? userRepository.findAll(pageable).getContent()
                : userRepository.findAllInId(List.of(ids), pageable);
```

2023-02-28 19:01 UTC, FanaticFiz approved these changes

2023-02-28 19:01 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/service/compilation/service/CompilationServiceImpl.java
> +    private Event getEvent(Event event) {
А ты не заметила что `getEvent` и `getEventById` очень похожи?
В тот момент когда два метода расположились рядом это можно было бы заметить!И из одного просто вызвать другой.

```
    private Event getEventById(Long eventId) {
        return eventRepository.findById(eventId)
                              .orElseThrow(() -> new NotFoundException("Событие не найдено или недоступно"));
    }

    private Event getEvent(Event event) {
        return getEventById(event.getId());
    }
```

2023-02-28 19:01 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/service/event/controller/EventController.java
> +/*    @GetMapping("/admin/events")
Что случилось?
Почему такой большой закомментированный кусок код?

2023-02-28 19:10 UTC, OxanaKutukova commented on main-service/src/main/java/ru/practicum/ewm/service/event/controller/EventController.java
> +/*    @GetMapping("/admin/events")
Да, я лопух.. :(((
Всегда комментирую рабочее решение, а потом начинаю его копию ломать, ну да я знаю, что гит мне в помощь в таких ситуациях, но пока еще не уверенно

2023-04-06 14:17 UTC, merged